import time 

print("o--o           o  ")
print("|   |          |  ")
print("O--o  o-o o-o -o- ")
print("|   | |   | |  |  ")
print("o--o  o   o-o  o  ")
                  
name = input("Аккаунт/Айди: ")
name2 = input("Прокси: ")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")

print("Почта: example@gmail.com | Пароль: ZXCTEMa")