import time 

print("o--o           o  ")
print("|   |          |  ")
print("O--o  o-o o-o -o- ")
print("|   | |   | |  |  ")
print("o--o  o   o-o  o  ")
                  
input("Аккаунт/Айди: ")
input("Прокси: ")
name = input("Login: ") 
name2 = input ("Password: ") 
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")
print("Бротинг...")

print("Почта: example@gmail.com | Пароль: ZXCTEMa")
